### ISSUE TITLE
chrome-extension:// scheme not valid in Auth0 UI

### ISSUE THREAD

**Issue by c0bra** [auth0-community/auth0-chrome#12]
It looks like it's impossible to add `chrome-extension://<YOUR APP ID>` as a Web Origin URL in the Auth0 admin interface.

Any suggestions?

**Comment by penseeartificielle** [comment]
it's because you have to put it in "Allowed Origins (CORS)" and not in "Allowed Web Origins" ^^

**Comment by beardaway** [comment]
Thanks a lot @penseeartificielle for providing this knowledge! It is correct.
