### ISSUE TITLE
Cannot read property 'getRedirectURL' of undefined

### ISSUE THREAD

**Issue by siauderman** [auth0-community/auth0-chrome#14]
Hi, my app was working in development but now that I have published it on the Chrome Web Store, it didn't work! I have updated my CORS url and callback urls with the new app ID already but it is still not working.
Here is the app URL: https://chrome.google.com/webstore/search/Caselist
![image](https://user-images.githubusercontent.com/14951259/41505007-903033e2-7231-11e8-9b78-270e06249e35.png)

**Comment by siauderman** [comment]
Sorry, I have solved the problem. It was a permission error as I forgot to add "identity" to the permissions.

**Comment by beardaway** [comment]
Thanks a lot @siauderman  for sharing it with the rest of community!
