### ISSUE TITLE
Authorization page could not be loaded 

### ISSUE THREAD

**Issue by killa-kyle** [auth0-community/auth0-chrome#15]
Starting this past Friday (8/17/18) I've been getting this error when trying to log in using a social provider (Salesforce). The login window appears as if it's working, then it closes and I get this error in the console. [I've attached a link to a video of this issue as well](https://www.dropbox.com/s/4nwdkfmpzkcljha/auth0issue.gif?dl=0)

`Error: Authorization page could not be loaded.
   at Object.callback (chrome-extension://eaonkakpkhppgedffnpohgknnhmclllk/node_modules/auth0-chrome/dist/auth0chrome.min.js:1:1850)
   at safeCallbackApply (extensions::uncaught_exception_handler:27:15)
   at handleResponse (extensions::sendRequest:67:7)`

**Comment by mdbiundo** [comment]
Hey, I was just having this issue, double check that you're using the correct extension ID in your Auth0 settings.

**Comment by beardaway** [comment]
Hey @killa-kyle  have you had time to check what @mdbiundo  suggested?

**Comment by killa-kyle** [comment]
@beardaway I did check. my configuration was correct at the time. the issue resolved itself days later, but not before I had written my own auth as a backup.

**Comment by beardaway** [comment]
Thanks a lot for letting us know! I'll close this one as we gradually go through PRs and issues and will step by step implement fixes and improvements suggestions.

**Comment by andreasvirkus** [comment]
Also getting this error. Double-checked my extension ID in Auth0's application settings.
Does the extension need to be published beforehand (since it needs to access `<extension-id>.chromiumapp.org`)?

**Comment by andreasvirkus** [comment]
Turns out the callback URL had to be `*.chromiumapp.org` (no `s`)...

**Comment by beardaway** [comment]
Thanks a lot for detecting that! I just merged your PR.
