### ISSUE TITLE
Impossible to renewal Token ID with Refresh Token

### ISSUE THREAD

**Issue by STK913** [auth0-community/auth0-chrome#19]
Hello,

I want to refresh the token as explained here (to regenerate the token ID before it expires): https://auth0.com/docs/tokens/refresh-token/current#use-a-refresh-token
But I can’t get a new token ID, while “openid offline_access” is present in the scope.

My request to https://xxxx.eu.auth0.com/oauth/token : 

> {
>   "grant_type": "refresh_token",
>   "client_id": "as32ad32adef45e4fz54",
>   "client_secret": "zefgerg4e4rg",
>   "refresh_token": "98reh5rttr4h",
>   "json": true
> }

The response:

> {
> “access_token”: “s5f4ddf5h45h4”,
> “expires_in”: 86400,
> “token_type”: “Bearer”
> }
-> id_token isn't present !

And my code for recover token:

> let options = {
>   scope: 'openid profile offline_access',
>   device: 'chrome-extension'
> };
> 
> new Auth0Chrome(Variables.AUTH0_DOMAIN, Variables.AUTH0_CLIENT_ID)
> .authenticate(options)
> .then(result => {
>   // Process
> });

Do you have an explanation, please ?

**Comment by STK913** [comment]
Is this a bug or a configuration problem?

**Comment by blinard** [comment]
Based on the Auth0 documentation it looks chrome extensions are treated as SPAs (Single Page Applications). The Auth0 SPA documentation calls out that SPAs can't use the Refresh Tokens. 

See: https://auth0.com/docs/api-auth/tutorials/silent-authentication#renew-expired-tokens

Instead, you likely want to just issue a silent authentication request. For guidance on that you can just scroll up from the previous link or reference the link below.

Silent Authentication: https://auth0.com/docs/api-auth/tutorials/silent-authentication

It looks like the auth0-chrome may support this with the ```interactive``` parameter in the ```authenticate``` method. When looking through the code, ```interactive``` doesn't appear to map to the ```prompt=none``` parameter referenced in the Auth0 docs above, so I'm not sure if the silent authentication works with auth0-chrome at the moment. I plan to do some experimentation with this flow myself shortly. I'll try to remember to come back and post and update once I do.

**Comment by blinard** [comment]
Follow-up: I was able to successfully execute a Silent Authentication request using the ```interactive``` parameter in the auth0-chrome package's ```authenticate``` method (just pass ```false``` as the 2nd param).

I'm not sure exactly how it works yet but it does seem to work.

**Comment by blinard** [comment]
Doh! I see how it works now. It passes the ```interactive``` parameter value through to the underlying ```chrome.identity.launchWebAuthFlow``` call.

**Comment by blinard** [comment]
Did a little further exploration/experimentation, if you want to use refresh_tokens within your Chrome extension it should be possible by making sure that your Api Settings within Auth0 have the 'Allow Offline Access' setting turned on (see image below). Then you'll also need to be sure to include the 'offline_access' scope in your initial authentication request.

![image](https://user-images.githubusercontent.com/585915/51509122-e54b2b80-1dac-11e9-8f6a-2e0f469d7bf2.png)

**Comment by andreasvirkus** [comment]
Just to clarify - chrome extensions are treated as `Native apps` and not as `SPAs` @blinard.

**Comment by LiteSoul** [comment]
I don't think this is working currently. Not only auth0-chrome library went through some changes lately, that "Allow Offline Access" option mentioned above doesn't seems to exists anymore.

We need a more definitive answer as to How to use Refresh Tokens on a Chrome Extension? Thank you.
