### ISSUE TITLE
No Clear Message When Login Succeeds - No User Profile Data Visible

### ISSUE THREAD

**Issue by iannyanes** [auth0-community/auth0-chrome#2]
When the user installs the sample extension and executes it for the first time. The Login screen pops out and asks for credentials, After successful login the user receives a message saying "You can now use the application" but there is no user profile information in sight in any part of the plugin.

Expected Behavior:

1. The user logs in using the credentials available
2. If the authentication is successful then the sample should show a message to the user
3. Part of the user profile should be shown in the success message or in a showable screen o the sample.

**Comment by chenkie** [comment]
@iannyanes can you move this over to https://github.com/auth0-community/auth0-chrome-sample ? :)

**Comment by iannyanes** [comment]
Done @chenkie Closing this ticket
