### ISSUE TITLE
Issue with Firefox

### ISSUE THREAD

**Issue by gurupras** [auth0-community/auth0-chrome#24]
### Description
This library works _almost_ flawlessly with Firefox. However, there is one massive issue that I'm unable to overcome. 

When logging in using this library, the login page will not auto-close on Firefox. It will stay stuck stating that it is `Waiting for <tenant>.auth0.com...`. If I manually close the page, then login fails. However, if I refresh the login page, then the page instantly closes and I'm logged in.

### Expected behaviour
The login page closes automatically after successful login.

### Actual behaviour 
The login page stays stuck stating that it is `Waiting for <tenant>.auth0.com...`

### Steps to reproduce the problem
  - Create auth0 account
  - Create new application of type native
  - Set up the callback and origin as per [this post](https://community.auth0.com/t/how-do-i-integrate-auth0-into-a-firefox-extension/17490/5)
  - Create a firefox extension that uses this library
  - Initialize it using:
```
const authResult = await new Auth0Chrome(auth0Env.AUTH0_DOMAIN, auth0Env.AUTH0_CLIENT_ID).authenticate({
  scope: 'openid profile offline_access email',
  audience: '<audience>',
  device: 'chrome-extension'
})
```

You could also try installing my [firefox extension v2.0.9.3](https://addons.mozilla.org/en-US/firefox/addon/twoseven-extension/)

### Language / Framework Versions

1. **Language used:** Javascript
2. **Framework used:** NA

### Testing environment

1. **Operating system:** Ubuntu 18.04
2. **Browser version:** Mozilla Firefox 65.0

**Comment by balmas** [comment]
FYI, this is a Firefox bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1528562 . The fix has been approved for Firefox release 67 beta 12.

**Comment by gurupras** [comment]
Ah! Thanks for letting me know. I'll get rid of my popup telling users to hit <kbd>ESC</kbd> if authentication hangs
