### ISSUE TITLE
logout doesn't clear SSO

### ISSUE THREAD

**Issue by omerdn1** [auth0-community/auth0-chrome#32]
### Description

Logout using `chrome.identity.launchWebAuthFlow` doesn't clear the SSO cookie in Auth0 and doesn't sign out the user from the IdP (Google, etc..)

### Expected behaviour

User should be logged out from IdP and should be able to login with Google using a different account after `chrome.identity.launchWebAuthFlow` has been initiated.

### Actual behaviour 

the SSO cookie in Auth0 isn't removed and the user isn't signed out from the IdP (Google, etc..)

### Steps to reproduce the problem
This is my code:
```
function logout() {
  const logoutUrl = new URL(`https://${env.AUTH0_DOMAIN}/v2/logout`);
  const params = {
    client_id: env.AUTH0_CLIENT_ID,
    returnTo: chrome.identity.getRedirectURL() + 'auth0'
  };
  logoutUrl.search = new URLSearchParams(params);
  chrome.identity.launchWebAuthFlow({
      'url': logoutUrl.toString()
    },
    function(responseUrl) {
      console.log(responseUrl);
    }
  );
}
```

Important to note that my extension is whitelisted both on **Allowed Callback URLs** and **Allowed Logout URLs**

**Comment by n-sviridenko** [comment]
Same here. Any updates on this? We use google social connection.

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
