### ISSUE TITLE
Using browser api

### ISSUE THREAD

**Issue by franciscolourenco** [auth0-community/auth0-chrome#33]
Any plans to sport the standard browser API?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API
https://github.com/mozilla/webextension-polyfill

Is it be possible to use https://auth0.com/docs/libraries/auth0-spa-js or any of the existing auth0 sdks together with `browser.identity.launchWebAuthFlow`, or do browser extensions require a custom implementation?

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
