### ISSUE TITLE
Sync logged in state between auth0-chrome and auth0-spa-js

### ISSUE THREAD

**Issue by franciscolourenco** [auth0-community/auth0-chrome#34]
I've configured auth0-chrome on the a extension and [auth0-spa-js](https://auth0.com/docs/libraries/auth0-spa-js) on a SPA. 
Both applications use the same Auth0 SSO domain, however when a user logs in/out in one application, they don't automatically get loggen in/out the other application. The user has to enter their credentials twice, to login in both applications, and logout twice in both applications. 

Is this behaviour expected, or is there something misconfigured? Thanks.

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
