### ISSUE TITLE
chrome.identity.launchWebAuthFlow doesn't share cookies with rest of browser

### ISSUE THREAD

**Issue by franciscolourenco** [auth0-community/auth0-chrome#35]
It seems to be currently impossible to benefit from Auth0 SSO authentication state sync using the _auth0-chrome_ SDK, because the `chrome.identity.launchWebAuthFlow` API which it uses, doesn't share cookies with the rest of the browser space. It requires the user to enter their credentials again, even if the user has already done so in a different web application using the [PKCE](https://auth0.com/docs/flows/concepts/auth-code-pkce) auth flow, for the same browser and tenant.

- https://bugs.chromium.org/p/chromium/issues/detail?id=365200
- https://bugs.chromium.org/p/chromium/issues/detail?id=907920

  

Judging by the other issues this API seems to have – like the lack of an address bar – and the level of inactivity in the bug reports aforementioned, it is unclear if/when these issues will be fixed.

A disclaimer should be added both to the README and to Auth0 docs, explaining this limitation. 

I would also be great if Auth0 could recommend a solution.

**Comment by andreasvirkus** [comment]
Also highly related:
https://bugs.chromium.org/p/chromium/issues/detail?id=340428#c7

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
Community.Auth0.com -- Thank you for your contributions.
