### ISSUE TITLE
Any ideas to work around Firefox internal uuid and CORS?

### ISSUE THREAD

**Issue by collinwu** [auth0-community/auth0-chrome#37]
### Description

`auth0-chrome` along with `webextension-polyfill` makes cross-browser web extension development great, but I'm having an issue with CORS suddenly as I realize I can't possibly whitelist each potential user's Firefox extension internal UUID that auth0 requires.

According to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources), the extension-uuid is randomly generated, but is static in Chrome. 

> `moz-extension://<extension-UUID>/images/my-image.png"`
> `<extension-UUID> is **not** your extension's ID.`
> This ID is randomly generated for every browser instance. This prevents websites from fingerprinting a browser by examining the extensions it has installed.

> In Chrome, an extension's ID is fixed. When a resource is listed in web_accessible_resources, it is accessible as `chrome-extension://<your-extension-id>/<path/to/resource>. `

To try and get around the issue, I've tried setting the allowed origins to: `moz-extension://*` in auth0 but it doesn't seem to be working.

Any ideas on how to approach this?

### Expected behaviour

Since Firefox extensions make requests from the internal UUID that's different for every client. This seems to be intentional by Mozilla, but without `moz-extension://*` support, I'm not sure how to make the extension work with Firefox.

### Actual behaviour 

The web extension complains: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<domain>.auth0.com/oauth/token. (Reason: CORS header 'Access-Control-Allow-Origin' missing).` This is followed by `(Reason: CORS request did not succeed).` 

All works fine if I whitelist each of my three machine's `moz-extension://<internal-uuid>`

### Steps to reproduce the problem

1. Follows steps in [Getting Started Guide](https://github.com/auth0-community/auth0-chrome#getting-started)
2. Caveat - change `Allowed Origins (CORS)` section to: `moz-extension://*`
3. Leverage [Webextension-polyfill](https://github.com/mozilla/webextension-polyfill) in other words, require/import library and replace `chrome` with `browser` namespace.
4. Initialize:

```
const authResult = await new Auth0Chrome(auth0Env.AUTH0_DOMAIN, auth0Env.AUTH0_CLIENT_ID).authenticate({
  scope: 'openid profile offline_access email',
  audience: '<audience>',
  device: 'chrome-extension'
})
```

### Language / Framework Versions

1. Javascript
2. No framework

### Testing environment

1. MacOS v10.15.2
2. Mozilla Firefox v71.0

### Screenshots

<img width="1279" alt="Screenshot 2019-12-31 02 58 31" src="https://user-images.githubusercontent.com/6867357/71619637-31d0e680-2b7a-11ea-97e5-a29f2b3988bf.png">

<img width="599" alt="Screenshot 2019-12-31 03 05 07" src="https://user-images.githubusercontent.com/6867357/71619669-5fb62b00-2b7a-11ea-901f-abdcf27bd4f0.png">

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
Community.Auth0.com -- Thank you for your contributions.
