### ISSUE TITLE
Lock configuration from chrome sign in

### ISSUE THREAD

**Issue by raguiar2** [auth0-community/auth0-chrome#38]
# Issue Report
I need to disable sign ups/some other lock config options from my chrome extension, but it's not allowed currently. There needs to be a way to configure the lock launched by the auth0 chrome extension

### Expected behaviour

You should be able to pass in a configuration object to either the authenticate method or the auth0chromeextension object that allows you to edit the lock as described in https://auth0.com/docs/libraries/lock/v11/configuration.

### Actual behaviour 

This is not possible today AFAIK.

**Comment by quitrk** [comment]
Subscribing to this, we also need to be able to pass some options when authenticating, like the 'initialScreen', in case user presses the sign up button

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
Community.Auth0.com -- Thank you for your contributions.
