### ISSUE TITLE
Login Button is Disabled after First Use

### ISSUE THREAD

**Issue by iannyanes** [auth0-community/auth0-chrome#4]
After the user successfully authenticates the first time the extension is being used, The "Login" button is unresponsive.

This can be solved after fixing Issue #2

**Comment by chenkie** [comment]
@iannyanes can you move this over to https://github.com/auth0-community/auth0-chrome-sample ? :)

**Comment by iannyanes** [comment]
Done @chenkie  I will close the issue then.
