### ISSUE TITLE
React build failed to minify the code

### ISSUE THREAD

**Issue by sib-wolf** [auth0-community/auth0-chrome#9]
Building a chrome extension with react and having some issues with npm build. Any assistance would be greatly appreciated! 

`
Failed to minify the code from this file:

 	./node_modules/auth0-chrome/dist/auth0chrome.js:183

Read more here: http://bit.ly/2tRViJ9
`

**Comment by alirezavalizade** [comment]
I have same issue!

**Comment by raduflp** [comment]
did anyone find a workaround?
